# Azure Pipelines
# https://aka.ms/yaml

name: DevSkim_VisualStudio_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger:
  batch: true
  paths:
    include:
    - DevSkim-VisualStudio-Extension/*
  branches:
    include:
    - master

stages:
- stage: Run Build Tests
  jobs:
  - job: Windows
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: '$(SolutionDirectory)'
        feedsToUse: 'select'
        vstsFeed: '73b0a75c-d420-4e77-95db-e81276361e42'
    - task: MSBuild@1
      inputs:
        solution: '$(SolutionDirectory)/Microsoft.DevSkim.VSExtension.Tests/Microsoft.DevSkim.VSExtension.Tests.csproj'
        platform: 'AnyCPU'
        configuration: 'Release'
        msbuildArguments: '/p:OutputPath=$(Build.BinariesDirectory)/Tests'
        restoreNugetPackages: false

- stage: Publish
  jobs:
  - job: publish
    displayName: Publish Visual Studio Extension
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: *TODO*